"""Write manuscript result tables from a committed experiment directory.

    python -m research.paper_tables --experiment research/results/<experiment_id>

Replaces the content between ``<!-- BEGIN GENERATED:<tag>-<block> -->`` and
``<!-- END GENERATED:<tag>-<block> -->`` in ``paper/manuscript.md``. The tag is
``llm`` for runs with an LLM judge and ``smoke`` otherwise. Refuses to use a
results directory whose artifacts no longer match its manifest.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from research.run import REPO_ROOT, verify_results
from research.systems import ABLATIONS, PRIMARY_SYSTEMS, SYSTEMS

MANUSCRIPT = REPO_ROOT / "paper" / "manuscript.md"
BLOCKS = ("primary", "operational", "comparisons", "ablation", "errors")


def _f(v, digits: int = 3) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return f"{v:.{digits}f}"
    return str(v)


def _ci(cis: dict, system: str, metric: str) -> str:
    e = cis[system][metric]
    if e["point"] is None:
        return "n/a"
    return f"{e['point']:.3f} [{_f(e['ci_low'])}, {_f(e['ci_high'])}]"


def _rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def render_blocks(exp_dir: Path) -> tuple[str, dict[str, str]]:
    manifest = json.loads((exp_dir / "manifest.json").read_text(encoding="utf-8"))
    metrics = json.loads((exp_dir / "metrics.json").read_text(encoding="utf-8"))
    cis = json.loads((exp_dir / "confidence_intervals.json").read_text(encoding="utf-8"))["systems"]
    disagreements = [
        json.loads(line) for line in (exp_dir / "disagreements.jsonl").read_text(encoding="utf-8").splitlines() if line
    ]
    systems = metrics["systems"]
    is_llm = manifest["judge"]["is_llm"]
    tag = "llm" if is_llm else "smoke"
    judge_name = manifest["judge"]["model"] if is_llm else "offline heuristic stand-in (NOT an LLM)"
    source = (
        f"_Source: `{_rel(exp_dir)}` · judge: {judge_name} · split(s) {manifest['dataset']['splits']} · "
        f"n={manifest['dataset']['n_cases']} · dataset `{manifest['dataset']['dataset_sha256'][:12]}` · "
        f"commit `{(manifest['git']['commit'] or 'unknown')[:7]}` · 95% percentile bootstrap, "
        f"{manifest['bootstrap']['iterations']} iterations, seed {manifest['bootstrap']['seed']}. "
        "Generated by `python -m research.paper_tables`; do not edit._"
    )
    standin_note = (
        ""
        if is_llm
        else "\n\n> Judge-based rows use the offline heuristic stand-in, not an LLM. They demonstrate the pipeline. "
        "They are **not** evidence for RQ1 about LLM judging. Only the Deterministic-only row is a real measurement."
    )

    def label(s: str) -> str:
        base = SYSTEMS[s].label
        return base if is_llm or SYSTEMS[s].judge_mode == "none" else f"{base} (stand-in)"

    blocks: dict[str, str] = {}
    rows = [
        "| System | Accuracy | Precision | Recall | Macro-F1 | FPR | FNR |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for s in PRIMARY_SYSTEMS:
        if s in systems:
            rows.append(
                f"| {label(s)} | {_ci(cis, s, 'accuracy')} | {_ci(cis, s, 'precision')} | {_ci(cis, s, 'recall')} | "
                f"{_ci(cis, s, 'macro_f1')} | {_ci(cis, s, 'false_positive_rate')} | {_ci(cis, s, 'false_negative_rate')} |"
            )
    blocks["primary"] = source + standin_note + "\n\n" + "\n".join(rows)

    rows = [
        "| System | Abstention | Human-review rate | Judge-gold agreement (κ) | Latency p50 / p95 ms | Cost/case USD |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for s in (*PRIMARY_SYSTEMS, *ABLATIONS):
        if s in systems:
            m = systems[s]
            ag = m["judge_human_agreement"]
            agree = "n/a" if ag.get("value") is None else f"{ag['value']:.3f} ({_f(ag.get('cohen_kappa'))})"
            cost = _f(m["cost_per_case_usd"], 6) if m["cost_per_case_usd"] is not None else "NOT MEASURED"
            rows.append(
                f"| {label(s)} | {_f(m['abstention_rate'])} | {_f(m['human_review_rate'])} | {agree} | "
                f"{_f(m['latency_ms']['p50'], 2)} / {_f(m['latency_ms']['p95'], 2)} | {cost} |"
            )
    review = [s for s in (*PRIMARY_SYSTEMS, *ABLATIONS) if s in systems and "review" in systems[s]]
    if review:
        rows += ["", "| System | Routed | Error capture | Routing precision | Selective accuracy | "
                     "Oracle-resolved accuracy (simulated reviewer) |", "|---|---:|---:|---:|---:|---:|"]
        for s in review:
            r = systems[s]["review"]
            sel = r["selective_on_unrouted"]
            rows.append(
                f"| {label(s)} | {r['routed']}/{systems[s]['n']} | {_f(r['error_capture_rate'])} | "
                f"{_f(r['routing_precision'])} | {_f(sel['accuracy'] if sel else None)} | "
                f"{_f(r['oracle_resolved']['accuracy'])} |"
            )
    blocks["operational"] = source + "\n\n" + "\n".join(rows)

    rows = ["| Comparison (B − A) | Δ accuracy [95% CI] | Δ macro-F1 [95% CI] | Δ FPR [95% CI] | McNemar p |",
            "|---|---:|---:|---:|---:|"]
    for key, c in metrics["comparisons"].items():
        if c["system_b"] in ABLATIONS:
            continue
        pb = c["paired_bootstrap"]

        def d(metric: str) -> str:
            e = pb[metric]
            if e["difference_b_minus_a"] is None:
                return "n/a"
            return f"{e['difference_b_minus_a']:+.3f} [{_f(e['ci_low'])}, {_f(e['ci_high'])}]"

        rows.append(f"| {label(c['system_b'])} − {label(c['system_a'])} | {d('accuracy')} | {d('macro_f1')} | "
                    f"{d('false_positive_rate')} | {c['mcnemar_exact']['p_value']:.3f} |")
    blocks["comparisons"] = source + "\n\n" + "\n".join(rows)

    rows = ["| Configuration | Macro-F1 [95% CI] | FPR | Δ macro-F1 vs full [95% CI] | Latency p50 ms | Review rate |",
            "|---|---:|---:|---:|---:|---:|"]
    if "B4_hybrid" in systems:
        b4 = systems["B4_hybrid"]
        rows.append(f"| Full hybrid | {_ci(cis, 'B4_hybrid', 'macro_f1')} | {_f(b4['automated']['false_positive_rate'])} | "
                    f"- | {_f(b4['latency_ms']['p50'], 2)} | {_f(b4['human_review_rate'])} |")
    names = {"A1_minus_rules": "− deterministic rules", "A2_minus_retrieval": "− retrieval",
             "A3_minus_judge": "− judge (lexical grader instead)", "A4_minus_routing": "− review routing"}
    for s in ABLATIONS:
        if s in systems:
            m = systems[s]
            comp = metrics["comparisons"].get(f"{s}_vs_B4_hybrid", {}).get("paired_bootstrap", {}).get("macro_f1")
            delta = (
                "n/a" if not comp or comp["difference_b_minus_a"] is None
                else f"{comp['difference_b_minus_a']:+.3f} [{_f(comp['ci_low'])}, {_f(comp['ci_high'])}]"
            )
            rows.append(f"| {names[s]} | {_ci(cis, s, 'macro_f1')} | {_f(m['automated']['false_positive_rate'])} | "
                        f"{delta} | {_f(m['latency_ms']['p50'], 2)} | {_f(m['human_review_rate'])} |")
    blocks["ablation"] = source + standin_note + "\n\n" + "\n".join(rows)

    rows = ["| System | Disagreements | False positives | False negatives | Abstained | Overconfident | "
            "Gold evidence not retrieved | Ambiguous-gold cases |", "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for s in (*PRIMARY_SYSTEMS, *ABLATIONS):
        if s not in systems:
            continue
        ds = [d for d in disagreements if d["system"] == s]

        def count(tag_name: str) -> int:
            return sum(1 for d in ds if tag_name in d["tags"])

        rows.append(
            f"| {label(s)} | {len(ds)} | {sum(1 for d in ds if d['human_label'] == 'pass' and d['system_label'] == 'fail')} | "
            f"{sum(1 for d in ds if d['human_label'] == 'fail' and d['system_label'] == 'pass')} | "
            f"{sum(1 for d in ds if d['system_label'] is None)} | {count('overconfident_judge_error')} | "
            f"{count('grounding_failure_gold_evidence_not_retrieved')} | {count('ambiguous_gold_label')} |"
        )
    missed: dict[str, list[str]] = {}
    for d in disagreements:
        if d["system"] == "B4_hybrid" and d["human_label"] == "fail":
            missed.setdefault(d["failure_category"], []).append(d["case_id"])
    fps = [d["case_id"] for d in disagreements if d["system"] == "B4_hybrid" and d["human_label"] == "pass"]
    rows += ["", "Hybrid (B4) false negatives by gold category: "
             + ("; ".join(f"{k}: {', '.join(v)}" for k, v in sorted(missed.items())) or "none") + ".",
             "Hybrid (B4) false positives: " + (", ".join(fps) or "none") + "."]
    blocks["errors"] = source + "\n\n" + "\n".join(rows)
    return tag, blocks


def apply_blocks(text: str, tag: str, blocks: dict[str, str]) -> str:
    for name, body in blocks.items():
        begin, end = f"<!-- BEGIN GENERATED:{tag}-{name} -->", f"<!-- END GENERATED:{tag}-{name} -->"
        pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), flags=re.DOTALL)
        if not pattern.search(text):
            raise SystemExit(f"manuscript is missing marker {begin}")
        text = pattern.sub(lambda _: f"{begin}\n{body}\n{end}", text)
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m research.paper_tables")
    parser.add_argument("--experiment", type=Path, required=True)
    parser.add_argument("--manuscript", type=Path, default=MANUSCRIPT)
    args = parser.parse_args(argv)
    problems = verify_results(args.experiment)
    if problems:
        raise SystemExit("refusing to use modified results: " + "; ".join(problems))
    manifest = json.loads((args.experiment / "manifest.json").read_text(encoding="utf-8"))
    if manifest["status"] != "complete":
        raise SystemExit(f"experiment status is {manifest['status']}, not complete")
    tag, blocks = render_blocks(args.experiment)
    text = args.manuscript.read_text(encoding="utf-8")
    args.manuscript.write_bytes(apply_blocks(text, tag, blocks).encode("utf-8"))
    print(f"updated {len(blocks)} '{tag}' blocks in {args.manuscript}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
